# permissions for end users to view rabbitmqexchanges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqexchange-viewer-role
rules:
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqexchanges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqexchanges/status
  verbs:
  - get
