# permissions for end users to edit rabbitmqbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqbinding-editor-role
rules:
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqbindings/status
  verbs:
  - get
