# permissions for end users to edit rabbitmqpermissons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqpermisson-editor-role
rules:
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqpermissons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqpermissons/status
  verbs:
  - get
