# permissions for end users to view rabbitmqpermissons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqpermisson-viewer-role
rules:
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqpermissons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqpermissons/status
  verbs:
  - get
