# permissions for end users to edit rabbitmqexchanges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqexchange-editor-role
rules:
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqexchanges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqexchanges/status
  verbs:
  - get
