# permissions for end users to view rabbitmqshovels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqshovel-viewer-role
rules:
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqshovels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.kokuwa.io
  resources:
  - rabbitmqshovels/status
  verbs:
  - get
