apiVersion: rabbitmq.kokuwa.io/v1beta1
kind: RabbitmqUser
metadata:
  name: rabbitmquser-sample
spec:
  # Add fields here
  name: bar
  tags: administrator
  secretRef:
    name: my-secret
    namespace: kiwios
    key: password
  clusterRef:
    name: rabbitmqcluster-sample
