apiVersion: rabbitmq.kokuwa.io/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster-sample
spec:
  host: http://rabbitmq.default.svc:15672
  user: admin
  secretRef:
    name: rabbitmq
    namespace: default
    key: rabbitmq-password
