apiVersion: rabbitmq.kokuwa.io/v1beta1
kind: RabbitmqExchange
metadata:
  name: rabbitmqexchange-sample
spec:
  name: rico-test
  vhost: /
  clusterRef:
    name: rabbitmqcluster-sample
  settings:
    type: "fanout"
    durable: true